; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nucleo_l432kc_stlink

[env]
platform = ststm32
board = nucleo_l432kc
framework = arduino

; Enable HW-Serial1
build_flags =
  -D HAVE_HWSERIAL1

; Enforce (unreleased) main branch from Github. Required for SerialUSB.baud() until >2.12.0 release (see https://github.com/stm32duino/Arduino_Core_STM32/pull/2892)
platform_packages =
    framework-arduinoststm32 @ https://github.com/stm32duino/Arduino_Core_STM32.git#main

; required Arduino libraries
lib_deps =
  https://github.com/yaacov/ArduinoModbusSlave.git

[env:nucleo_l432kc_dfu]
upload_protocol = dfu
upload_port = 0483:df11

[env:nucleo_l432kc_stlink]
upload_protocol = stlink
